Entities/Semester.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Musikania2017.API.Entities
{
    public class Semester
    { 
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<LessonsDay> LessonsDays { get; set; }
            = new List<LessonsDay>();
    }
}

Controllers/SemesterController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Musikania2017.API.Models;
using Musikania2017.API.Services;
using System.Linq;

namespace Musikania2017.API.Controllers
{
    [Route("api/semesters")]
    public class SemesterController : Controller
    {
        private IMusikaniaRepository _musikaniaRepository;

        public SemesterController(IMusikaniaRepository musikaniaRepository)
        {
            _musikaniaRepository = musikaniaRepository;
        }

    /// <summary>
    /// Gets the availiable semesters
    /// </summary>
    /// <returns></returns>
        [HttpGet]
        public IActionResult GetSemesters()
        {
            var result = _musikaniaRepository.GetSemesters();

            if (!result.Any())
            {
                return NotFound();
            }

        return Ok(result);

        }

        /// <summary>
        /// Gets a semester by Id
        /// </summary>
        /// <param name="semesterId"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("{semesterId}", Name ="GetSemesterById")]
        public IActionResult GetSemesterById(int semesterId)
        {
            var result = _musikaniaRepository.GetSemester(semesterId);

            if (result == null)
            {
                return NotFound();
            }

            return Ok(result);
        }

        /// <summary>
        /// Creates a new semester
        /// </summary>
        /// <param name="semester"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult CreateSemester(
            [FromBody] SemesterForCreationDto semester)
        {
            if (semester == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var finalSemester = Mapper.Map<Entities.Semester>(semester);

            _musikaniaRepository.CreateSemester(finalSemester);

            if (!_musikaniaRepository.Save())
            {
                return StatusCode(500, "A proplem happened while handeling your request.");
            }

            var createdSemesterToReturn = Mapper.Map<Models.SemesterDto>(finalSemester);

            return CreatedAtRoute("GetSemesterById", new
            { semesterId = createdSemesterToReturn.Id }, createdSemesterToReturn);

        }

        /// <summary>
        /// Deletes a semester by Id
        /// </summary>
        /// <param name="semesterId"></param>
        /// <returns></returns>
        [HttpDelete]
        [Route("{semesterId}")]
        public IActionResult DeleteSemester(int semesterId)
        {
            var semester = _musikaniaRepository.GetSemester(semesterId);

            if (semester == null)
            {
                return NotFound();
            }

            _musikaniaRepository.DeleteSemester(semester);

            if (!_musikaniaRepository.Save())
            {
                return StatusCode(500, "A proplem happened while handeling your request.");
            }

            return NoContent();
        }

    }
}

Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;
using Musikania2017.API.Models;
using Musikania2017.API.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Musikania2017.API.Controllers
{
    public class TestController : Controller
    {
        private IMusikaniaRepository _musikaniaRepository;

        public TestController(IMusikaniaRepository musikaniaRepository)
        {
            _musikaniaRepository = musikaniaRepository;
        }

        public IActionResult Index()
        {
            return View(_musikaniaRepository.GetStudentsForTesting());
        }

        public IActionResult Semester()
        {
            return View(_musikaniaRepository.GetSemesters());
        }

        public IActionResult Create()
        {
            return View();
        }

    }
}

Views/Test/Create.cshtml
@model Musikania2017.API.Models.SemesterForCreationDto

<h1>Create</h1>

<form asp-controller="Test" asp-action="Create">
    <input asp-for"Name" />
    <input type="submit" />
</form>

@Component.InvokeAsync("Create")

Views/Test/Index.cshtml
@model IEnumerable<Musikania2017.API.Entities.ModifiedStudent>

@{
    ViewData["Title"] = "Test Page";
}

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    th, td {
        padding: 5px;
    }

    th {
        text-align: left;
    }
</style>


<h1>Studentzzz</h1>

<table>
    <tr>
        <th>
            Name
        </th>
        <th>
            Start time
        </th>
        <th>
            End time
        </th>
        <th>
            Email
        </th>
    </tr>
    @foreach (var item in Model)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LessonStartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LessonEndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EMailAddress)
            </td>
        </tr>
    }
</table>

Views/Test/Semester.cshtml
@model IEnumerable<Musikania2017.API.Entities.Semester>

<h1>Semester</h1>

@foreach (var item in Model)
{
    @Html.DisplayFor(modelitem => item.Name)
    <br />
}